name: Install chocolatey
on: workflow_dispatch
jobs:
  Windows:
    runs-on: windows-latest
    steps:
    - name: Setup and Test Chocolatey
      shell: pwsh
      run: |
        Get-ExecutionPolicy
        Set-ExecutionPolicy Bypass -Scope Process
        Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))
        choco upgrade chocolatey
        choco
        choco install gh
